# # workflow
# #yml/yaml -> is a markup language

# #series of instruction/steps 
# #this can be read by machine to automate tasks


# #key-value

# title: Website name
# discription: A website for uploading content


# #array
# tags:
#   -tech
#   -image
#   -creative

# #object
# addaress:
#  street: main market
#  city: kota
#  state: Rajsthan

# #github actions
# #env variables
# value: ${{env.VALUE}}
# variable: ${{github.VARIABLE_NAME}}
# #   code: ${{secrets.AWS_Access_key}}
name: Github action ofr
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Print Node version
        run: node --version 


